FROM node:20.15.1-slim as build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --force

COPY . .

RUN npm run build

# TODO falta añadir para el despliegue en producción
FROM  node:20.15.1-slim

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/dist /app

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
