export const ALL_UNIVERSITIES = [
    "U. a Distancia de Madrid",
    "U. Alfonso X el Sabio",
    "U. Antonio de Nebrija",
    "U. Autónoma de Madrid",
    "U. Autónoma de Barcelona",
    "U. Camilo José Cela",
    "U. Cardenal Herrera-CEU",
    "U. Carlos III de Madrid",
    "U. Complutense de Madrid",
    "U. CEU Fernando III",
    "U. Católica San Antonio",
    "U. Católica Santa Teresa de Jesús de Ávila",
    "U. de A Coruña",
    "U. de Alcalá",
    "U. de Alicante",
    "U. de Almería",
    "U. de Barcelona",
    "U. de Burgos",
    "U. de Cádiz",
    "U. de Cantabria",
    "U. de Castilla-La Mancha",
    "U. de Córdoba",
    "U. de Deusto",
    "U. de Diseño, Innovación y Tecnología (UDIT)",
    "U. de Extremadura",
    "U. de Girona",
    "U. de Granada",
    "U. de Huelva",
    "U. de Jaén",
    "U. de La Laguna",
    "U. de La Rioja",
    "U. de las Hespérides",
    "U. de Las Palmas de Gran Canaria",
    "U. de León",
    "U. de Lleida",
    "U. de Málaga",
    "U. de Murcia",
    "U. de Oviedo",
    "U. de Salamanca",
    "U. de Santiago de Compostela",
    "U. de Sevilla",
    "U. de Valladolid",
    "U. de Vic-Universidad Central de Catalunya",
    "U. de Zaragoza",
    "U. del Atlántico Medio",
    "U. del País Vasco",
    "Euskal Herriko Unibertsitatea",
    "U. Euneiz",
    "U. Europea de Canarias",
    "U. Europea de Madrid",
    "U. Europea de Atlántico",
    "U. Europea de Miguel de Cervantes",
    "U. Fernando Pessoa-Canarias (UFP-C)",
    "U. Francisco de Vitoria",
    "U. Intercontinental de la Empresas",
    "U. Internacional de Andalucía",
    "U. Internacional de la Empresa",
    "U. Internacional de la Rioja",
    "U. Internacional Isabel I de Castilla",
    "U. Internacional Menéndez Pelayo",
    "U. Internacional Villanueva",
    "U. Jaume I de Castellón",
    "U. Loyola Andalucía",
    "U. Miguel Hernández de Elche",
    "U. Nacional de Educación a Distancia",
    "U. Pablo de Olavide",
    "U. Politécnica de Cartagena",
    "U. Politécnica de Cataluña",
    "U. Politécnica de Madrid",
    "U. Politécnica de Valencia",
    "U. Pompeu Fabra",
    "U. Pontificia de Salamanca",
    "U. Pública de Navarra",
    "U. Ramón Llull",
    "U. Rey Juan Carlos",
    "U. Rovira i Virgili",
    "U. San Pablo-CEU",
    "U. Tecnológica Atantico-Mediterraneo",
    "U. Abat Oliba CEU",
    "U. de les Illes Balears",
    "U. de Valencia",
    "U. Internacional de Cataluña",
    "U. Oberta de Cataluña"
];

export const ACADEMIC_FIELDS = [
    "Actividad física y ciencias del deporte",
    "Arquitectura, construcción, edificación y urbanismo, e ingeniería civil",
    "Biología y genética",
    "Bioquímica y biotecnología",
    "C. agrarias y tecnología de los alimentos",
    "C. biomédicas",
    "C. de la educación",
    "C. de la tierra",
    "C. del comportamiento y psicología",
    "C. económicas, administración y Dir. Empresas, marketing, comercio, contabilidad y turismo",
    "C. medioambientales y ecología",
    "CCSS, trabajo social, RRLL, RRHH, sociología, CCPP y RRII",
    "Derecho y especialidades jurídicas",
    "Enfermería",
    "Estudios de género y estudios feministas",
    "Farmacia",
    "Filología, estudios clásicos, traducción y lingüística",
    "Física y astronomía",
    "Fisioterapia, podología, nutrición y dietética, terapia ocupacional, óptica y optometría y logopedia",
    "Historia, arqueología, geografía, filosofía y humanidades",
    "Historia del arte y de la expresión artística y bellas artes",
    "Industrias Culturales: diseño, animación, cinematografía y producción audiovisual",
    "Ing. eléctrica, Ing. electrónica e Ing. de la telecomunicación",
    "Ing. industrial, Ing. mecánica, Ing. automática, Ing. de la Organización industrial e Ing. de la navegación",
    "Ing. informática y de sistemas",
    "Ing. química, ing. de los materiales e Ing. del medio natural",
    "Interdisciplinar",
    "Matemáticas y estadística",
    "Medicina y Odontología",
    "Periodismo, comunicación, publicidad y RRPP",
    "Química",
    "Veterinaria"
];

export const ACADEMIC_BRANCHES = [
    "Artes y Humanidades",
    "Ciencias",
    "Ciencias de la Salud",
    "Ciencias Sociales y Jurídicas",
    "Ingeniería y Arquitectura"
]

export const ACADEMIC_LEVEL = [
    "Grado",
    "Máster",
    "Doctorado"
];